---
title: "Ejercicios."
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##EJERCICIOS - FUNDAMENTOS DE CALCULO.
######Jorge Fuertes

###Instalamos y cargamos las librerias necesarias.
```{r}
#install.packages(mosaicCalc)
library(mosaicCalc)
#install.packages(mosaic)
library(mosaic)
```

###Ejercicio 1
```{r}
#Using D(), find the derivate of:
g = mosaicCalc::D(3*x^2-2*x+4 ~ x)
g

#a)Value of the derivate if x=0:
g(0)

#b)What does a graph of the derivate function look like?
plotFun(g, x.lim=range(0,10))
#B -> Positive sloping line
```

###Ejercicio 2
```{r}
#Using D(), find the derivate of:
d = mosaicCalc::D(5*exp(.2*x) ~ x)
d

#a)Value of the derivate if x=0:
d(0)

#b)Plot out both the original expression and its derivate. How are they related at each other?
plotFun(5*exp(.2*x) ~ x, x.lim=range(0,10))
plotFun(d, x.lim=range(0,10))
#B -> Same exponential shape, but different initial values.

```

###Ejercicio 3
```{r}
#Use D() to finde the derivate of e^(-(x^2))
f = mosaicCalc::D(exp(-(x^2)) ~ x)
f

#Graph the derivate from x=-2 to 2
plotFun(f, x.lim=range(-2,2))

#What does the graph look like?
#C -> A positive wave followed by a negative wave.
```

###Ejercicio 4
```{r}
#What will be the value of this derivate?
c = mosaicCalc::D(fred^2 ~ ginger)
c
plotFun(c)
#C -> A positive sloping lane
```

###Ejercicio 5
```{r}
#Use D() to find the 3rd derivate of:
v = mosaicCalc::D(cos(2*t) ~ t&t&t)
v

#What is it?
#D -> 8sin(2t)

#What is the 4th derivate?
v1 = mosaicCalc::D(cos(2*t) ~ t&t&t&t)
v1
#E -> 16sin(2t)
```

###Ejercicio 6
```{r}
#Compute and graph the 4th derivate of:
h = mosaicCalc::D(cos(2*t^2) ~ t&t&t&t)
h

#What does the graph look like?
plotFun(h, x.lim = range(0,5))
#C -> A cosine whose amplitude increases and whose period decreases as t gets bigger.

#What functions appear in the complicated expresion?
#C -> cos, sin, squaring, multiplication and addition.
```

###Ejercicio 7


```{r}
#Use D() to compute several derivate functions:
m=mosaicCalc::D(x*sin(y)~x)
m
m1=mosaicCalc::D(x*sin(y)~y)
m1
m2=mosaicCalc::D(m(x,y)~x)
m2
m3=mosaicCalc::D(m(x,y)~y)
m3
```

```{r}
#And these two mixed partials:
m4=mosaicCalc::D(x*sin(y)~x&y)
m4
m5=mosaicCalc::D(x*sin(y)~y&x)
m5
```

```{r}
#The partial with respect to x and to y are identical - FALSE
m(2,3)
m1(2,3)

m(5,8)
m1(5,8)

m(-3,2)
m1(-3,2)
```

```{r}
#The second partials with respect to x and to y are identical - FALSE
m2(2,3)
m3(2,3)

m2(5,8)
m3(5,8)

m2(-3,2)
m3(-3,2)
```
```{r}
#The two mixed partials are identical. That is, it doesnt matter whether you differentiate first with respect to x and then y, or vice versa - FALSE
m4(2,3)
m5(2,3)

m4(5,8)
m5(5,8)

m4(-3,2)
m5(-3,2)
```














































